// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApnXgCnAf4cmwyaE2PUfV0eutWHQ6iZv8',
    appId: '1:367451013890:web:b66f98c54d57826692781b',
    messagingSenderId: '367451013890',
    projectId: 'eye-ai-3bb25',
    authDomain: 'eye-ai-3bb25.firebaseapp.com',
    storageBucket: 'eye-ai-3bb25.firebasestorage.app',
    measurementId: 'G-KBJN6G6FSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN1GXTQ8jTDWu8iVmkV-27opnKPMEvGKI',
    appId: '1:367451013890:android:02c6426fd71ecafb92781b',
    messagingSenderId: '367451013890',
    projectId: 'eye-ai-3bb25',
    storageBucket: 'eye-ai-3bb25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8JaENtvwxtTJ6r-Km8s-3NtrEicIIcNc',
    appId: '1:367451013890:ios:488d9c6b57184f1d92781b',
    messagingSenderId: '367451013890',
    projectId: 'eye-ai-3bb25',
    storageBucket: 'eye-ai-3bb25.firebasestorage.app',
    iosBundleId: 'com.example.optApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8JaENtvwxtTJ6r-Km8s-3NtrEicIIcNc',
    appId: '1:367451013890:ios:488d9c6b57184f1d92781b',
    messagingSenderId: '367451013890',
    projectId: 'eye-ai-3bb25',
    storageBucket: 'eye-ai-3bb25.firebasestorage.app',
    iosBundleId: 'com.example.optApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApnXgCnAf4cmwyaE2PUfV0eutWHQ6iZv8',
    appId: '1:367451013890:web:e9625783c15e4bd192781b',
    messagingSenderId: '367451013890',
    projectId: 'eye-ai-3bb25',
    authDomain: 'eye-ai-3bb25.firebaseapp.com',
    storageBucket: 'eye-ai-3bb25.firebasestorage.app',
    measurementId: 'G-R99N62T2BP',
  );
}
